language: cpp
sudo: enabled
compiler: gcc

before_install:
  - sudo apt-get -qq update

os:
  - linux

addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - make
    - autoconf
    - g++

script:
  - make
  - make test

env:
  global:
    - MAKEFLAGS="-j 8"